# Generated by Django 4.0 on 2021-12-31 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='creater',
            new_name='creator',
        ),
    ]
