# Generated by Django 4.0 on 2022-01-04 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_bid_bid_bid_offer_alter_bid_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_offer',
            new_name='bid',
        ),
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 11, 23, 11, 93382)),
        ),
    ]
