# Generated by Django 4.0 on 2022-01-04 17:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_rename_auctions_bid_auction_alter_bid_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 17, 18, 2, 278645)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currentbid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='listing',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='auctions.listing'),
        ),
    ]
