# Generated by Django 4.0 on 2022-01-05 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_bid_created_alter_listing_currentbid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 6, 29, 56, 940236)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currentbid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
