# Generated by Django 4.0 on 2022-01-05 08:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_bid_created_alter_listing_currentbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 8, 17, 46, 389987)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default='No category yet!', on_delete=django.db.models.deletion.CASCADE, related_name='similar_listings', to='auctions.category'),
        ),
    ]
